  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/post/"

  [[main]]
  name = "Publications"
  weight = 300
  identifier = "publications"
  url = "/publications/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"