  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Blog"
  weight = 600
  identifier = "blog"
  url = "/posts/"

  [[main]]
  name = "Publications"
  weight = 300
  identifier = "publications"
  url = "/publications_compressed/"

  [[main]]
  name = "Teaching"
  weight = 400
  identifier = "teaching"
  url = "/teaching/"

  [[main]]
  name = "Software"
  weight = 500
  identifier = "software"
  url = "/software/"

  [[main]]
  name = "CV"
  weight = 550
  identifier = "cv"
  url = "/cv/"

  [[main]]
  name = "Food"
  weight = 600
  identifier = "food"
  url = "https://www.pritirrecetas.com/en/"


  [[main]]
  name = "Other"
  weight = 700
  identifier = "other"

  [[main]]
  name = "Paper Writing"
  weight = 710
  identifier = "paper-writing"
  url = "/projects/paper-writing/"
  parent = "other"  

  [[main]]
  name = "New Students"
  weight = 720
  identifier = "new-students"
  url = "/projects/new-students/"
  parent = "other"

  [[main]]
  name = "Art?"
  weight = 730
  identifier = "art"
  url = "/projects/art/"
  parent = "other"