  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Blog"
  weight = 600
  identifier = "blog"
  url = "/post/"

  [[main]]
  name = "Publications"
  weight = 300
  identifier = "publications"
  url = "/publications/"

  [[main]]
  name = "Teaching"
  weight = 400
  identifier = "teaching"
  url = "/teaching/"

  [[main]]
  name = "Software"
  weight = 500
  identifier = "software"
  url = "/software/"

  [[main]]
  name = "Food"
  weight = 600
  identifier = "food"
  url = "https://www.pritirrecetas.com/en/"